#------------------------------------------#
# Mosquito Config File		   #
#------------------------------------------#

LOGFILE_PATH: 'MOSQUITO_POP_LOGS_PATH/mosquito_model_logs.log' # (e.g., 'logs/mosquito_model_logs.log')
OUTPUT_DIR: 'MOSQUITO_POP_OUTPUT_PATH' # (e..g., 'output/')
MODEL_RUN_SCRIPTS: 'model_scripts/'

# Inputs output
INPUTS:
  ENVIRONMENTAL_FORCING_DIR : 'MOSQUITO_POP_INPUT_PATH/elm_output' # (e..g., 'input/ELM_output')
  HYDROPOPS : 'MOSQUITO_POP_INPUT_PATH/hpu_shapefiles' # (e..g., 'input/hpu_shapefiles' # shapefile/geojson)

PARAMETERS:
  MOSQ_PARAMS_STD:
    PsiEggs: 232403      # first parameter of Eyring equation for egg development rate
    AEE: 46229          # activation energy parameter of Eyring equation for egg development (negative)
    ThetaLP: 1.161e-04  # first parameter of Briere equation for larval-pupal development rate
    TMLP: 34.2         # maximum temperature for Larval-pupal development rate in Briere equation
    IntAd: -0.111252    # intercept controling rate at which adults progress through embryonation
    Coef1Ad: 0.013427   # slope controling rate at which adults progress through embryonation
    PsiAd: 133227    # first parameter of Eyring equation for adult mortality rate
    AEAd: 53135         # activation energy parameter of Eyring equation for adult mortality (negative)
    Cutoff: 10.07     # temperature cutoff below which no development happens fitted to larvae-pupae.
  MOSQ_PARAMS_FITTED:
    DiapInt: -0.523761651159681
    DiapCoef1: 0.667325149723675
    OvipRate: 2.92473418191717
    alpha1: -6.04688716954606
    beta1: -37.0752836376234
    init: 9.10676986603379
  WETNESS_INDEX:
    WaterLevel: 1
    Precip: 0

