#------------------------------------------#
# Mosquito Config File		   #
#------------------------------------------#

LOGFILE_PATH: 'logs/mosquito_model_logs.log'
OUTPUT_DIR: 'output/'
MODEL_RUN_SCRIPTS: 'model_scripts/model_run.R'

# Inputs output
INPUTS:
  ENVIRONMENTAL_FORCING_DIR : 'input/HPU_forcing_data'
  HYDROPOPS : 'input/HPUs.geojson' # shapefile/geojson

DUMMY:
  MOSQ_PARAMS_STD:
    PsiEggs: 32270      # first parameter of Eyring equation for egg development rate
    AEE: 41281          # activation energy parameter of Eyring equation for egg development (negative)
    ThetaLP: 9.217e-05  # first parameter of Briere equation for larval-pupal development rate
    TMLP: 36.09         # maximum temperature for Larval-pupal development rate in Briere equation
    IntAd: -0.111252    # intercept controling rate at which adults progress through embryonation
    Coef1Ad: 0.013427   # slope controling rate at which adults progress through embryonation
    PsiAd: 1.568e+12    # first parameter of Eyring equation for adult mortality rate
    AEAd: 91730         # activation energy parameter of Eyring equation for adult mortality (negative)
    Cutoff: 9.154     # temperature cutoff below which no development happens fitted to larvae-pupae.
  MOSQ_PARAMS_FITTED:
    DiapInt: 0.9360025
    DiapCoef1: 0.4219935
    OvipRate: 4.3826252
    alpha1: -7.6602856
    beta1: -4223.7036434
    init: 34.0566217
    
