### Model Run
mosq.model <- function(parameters,hpu_MHI,forcing_data){
  #### From pbm-model-test-fxn.R ### 
  #### Changes will be noted ##
    #### Step 1: Source Model Functions ####
  ### Paths have changed ##
    # call CulexSimFunc
    source(paste0(config_data$MODEL_RUN_SCRIPTS,"culex_simulation_function.R"))
    # call cpmod
    source(paste0(config_data$MODEL_RUN_SCRIPTS,"single_step_time_age.R"))
    # call ConvolveFunc
    source(paste0(config_data$MODEL_RUN_SCRIPTS,"convolution_function.R"))
  #### Change from source: external forcing data is input rather than generated by function ##
    # #call the function which will read in the format and external data sources
    # # i.e. Wetness (Precip,Water Levels, etc), Temperature, and Daylight hrs
    # source("mosquito-pbm/code/model-source-functions/external_data_import_function.R")
  ####
  ### For Testing ##
  # parameters <- parameter_vec
  # hpu_MHI <- MHI_i
  # forcing_data <- forcing_data_i
  ###
  # From Source script: Not needed as paramters are already appropriately structured 
  # parms = c(DiapInt = p_fit['DiapInt', 'fit_parameters'],       # diapause intercept for logistic regression model
  #           DiapCoef1 =  p_fit['DiapCoef1', 'fit_parameters'],     # (negative) slope proportion in diapause changes with respect to day length
  #           PsiEggs = p_std['PsiEggs'][[1]],      # first parameter of Eyring equation for egg development rate
  #           AEE = p_std['AEE'][[1]],          # activation energy parameter of Eyring equation for egg development (negative)
  #           ThetaLP = p_std['ThetaLP'][[1]],  # first parameter of Briere equation for larval-pupal development rate
  #           TMLP =p_std['TMLP'][[1]],         # maximum temperature for Larval-pupal development rate in Briere equation
  #           IntAd = p_std['IntAd'][[1]],    # intercept controling rate at which adults progress through embryonation
  #           Coef1Ad = p_std['Coef1Ad'][[1]],   # slope controling rate at which adults progress through embryonation
  #           PsiAd = p_std['PsiAd'][[1]],    # first parameter of Eyring equation for adult mortality rate
  #           AEAd = p_std['AEAd'][[1]],         # activation energy parameter of Eyring equation for adult mortality (negative)
  #           Cutoff = p_std['Cutoff'][[1]],       # temperature cutoff below which no development happens fitted to larvae-pupae.
  #           OvipRate =  p_fit['OvipRate', 'fit_parameters'],    # oviposition rate.
  #           alpha1 =  p_fit['alpha1', 'fit_parameters'],        # controls Culex density dependent mortality
  #           beta1 =  p_fit['beta1', 'fit_parameters'],         # adjusts Culex density dependence as a function of water level
  #           init =  p_fit['init', 'fit_parameters'])          # This is the initial condition.
  ## From Source Script: read external data from forcing_data instead
  # Import external inputs
  # external.signal<-external.data.import(wetness_str = wetness_str,location_str = location_str,dates_str = "test") 
  # input1_Temp<-external.signal$Temperature
  # input2_DayHrs<-external.signal$DaylightHrs
  # input3_Wet<-external.signal$Wetness
  ##
  
  ## Added: need to use Habitat Index and generate daylight hrs
  ## Generate Wetness Index ####
  forcing_data$WetnessIndex <- hpu_MHI*forcing_data$precip_cm
  ## Calculate Daylight hours
  forcing_data$Daylight_hrs <- 0*forcing_data$temp_C + 1### Needs to be generated! 
  
  ## Assign to input vectors
  input1_Temp <- forcing_data$temp_C
  input2_DayHrs <- forcing_data$Daylight_hrs
  input3_Wet <- forcing_data$WetnessIndex 
  
  times<-seq(0,length(forcing_data$date)-1) ### changed 
  # daysteps <- external.signal$Daystep
  
  # Run Model 
  model_out <- data.frame(CulexSimFunc(times, parms=parameters, input1_Temp, input2_DayHrs, input3_Wet))
  #return(cbind(ActMosq=model_out[[1]],TotMosq=model_out[[2]],times,input1_Temp,input2_DayHrs,input3_Wet,daysteps))
  # return(cbind(data.frame(model_out),times,input1_Temp,input2_DayHrs,input3_Wet,daysteps))
  
  
  output <- model_out$TotMosq
  return(output)
}


# pbm.mosq.test <- function(wetness_str,location_str,p_std,p_fit){
#   #### Step 1: Source Model Functions ####
#   # call CulexSimFunc
#   source("mosquito-pbm/code/model-source-functions/culex_simulation_function.R")
#   # call cpmod
#   source("mosquito-pbm/code/model-source-functions/single_step_time_age.R")
#   # call ConvolveFunc
#   source("mosquito-pbm/code/model-source-functions/convolution_function.R")
#   #call the function which will read in the format and external data sources
#   # i.e. Wetness (Precip,Water Levels, etc), Temperature, and Daylight hrs 
#   source("mosquito-pbm/code/model-source-functions/external_data_import_function.R")
#   p_fit_num <- as.vector(p_fit$fit_parameters)
#   p_std_num <- as.vector(p_std)  # needs to be a vector NOT a named number
#   parms = c(DiapInt = p_fit_num[1],       # diapause intercept for logistic regression model
#             DiapCoef1 = p_fit_num[2],     # (negative) slope proportion in diapause changes with respect to day length
#             PsiEggs = p_std_num[1],      # first parameter of Eyring equation for egg development rate
#             AEE = p_std_num[2],          # activation energy parameter of Eyring equation for egg development (negative)
#             ThetaLP = p_std_num[3],  # first parameter of Briere equation for larval-pupal development rate
#             TMLP =p_std_num[4],         # maximum temperature for Larval-pupal development rate in Briere equation
#             IntAd = p_std_num[5],    # intercept controling rate at which adults progress through embryonation
#             Coef1Ad = p_std_num[6],   # slope controling rate at which adults progress through embryonation
#             PsiAd = p_std_num[7],    # first parameter of Eyring equation for adult mortality rate
#             AEAd = p_std_num[8],         # activation energy parameter of Eyring equation for adult mortality (negative)
#             Cutoff = p_std_num[9],       # temperature cutoff below which no development happens fitted to larvae-pupae.
#             OvipRate = p_fit_num[3],    # oviposition rate.
#             alpha1 = p_fit_num[4],        # controls Culex density dependent mortality
#             beta1 = p_fit_num[5],         # adjusts Culex density dependence as a function of water level
#             init = p_fit_num[6])          # This is the initial condition.
#   # Import external inputs
#   external.signal<-external.data.import(wetness_str = wetness_str,location_str = location_str,dates_str = "test") 
#   input1_Temp<-external.signal[,1]
#   input2_DayHrs<-external.signal[,2]
#   input3_Wet<-external.signal[,3]  
#   
#   times<-external.signal[,4]
#   daysteps <- external.signal[,5]
#   
#   # Run Model 
#   model_out <- CulexSimFunc(times, parms, input1_Temp, input2_DayHrs, input3_Wet)
#   return(cbind(ActMosq=model_out[[1]],TotMosq=model_out[[2]],times,input1_Temp,input2_DayHrs,input3_Wet,daysteps))
#   
# }
